name: ClearScreen
author: P1xel1ze
main: au.p1xel1ze.Cls
version: 0.2
description: Clears the server console
api-version: 1.21.11
commands:
   cls:
      description: Clears the server console
      usage: /cls
