name: ClearScreen
author: P1xel1ze
main: au.p1xel1ze.cls.Bukkit
version: 1.0
description: Clears the server console
api-version: 1.21
commands:
   cls:
      description: Clears the server console
      usage: /cls
